[package]
name = "lockdin-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
log = "0.4.29"
env_logger = "0.11.8"
dotenv = "0.15.0"
serde = { version = "1.0.148", features = ["derive"] }
actix-cors = "0.7.1"
sqlx = { version = "0.8.6", features = ["chrono", "macros", "postgres", "runtime-tokio-native-tls"] }
async-trait = "0.1.89"
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
reqwest = { version = "0.13.1", features = ["json"] }
uuid = { version = "1.20.0", features = ["v4", "v7"] }
chrono = { version = "0.4.43", features = ["serde"] }
serde_json = "1.0.149"
tokio = "1.49.0"

[dev-dependencies]
mockall = "0.13.1"
